MODEL:
  WEIGHTS: 'weights/r50_deformable_detr_plus_iterative_bbox_refinement-checkpoint.pth'
  MASK_ON: True
  LOSS:
    SEGM_MASK_COEF: 4.0
    SEGM_DICE_COEF: 4.0

SOLVER:
  BASE_LR: 0.0001
  LR_BACKBONE: 0.00001
  EPOCHS: 25
  STEPS: [15, ]

TEST:
  NUM_OUT: 50






