# This mask head is not train from scratch, thus we change lrs
MODEL:
  WEIGHTS: 'weights/swinL_SYN_deformable_detr_pre-trianed_segmentation.pth'
  BACKBONE: 'resnet101'
  SHIFT_CLASS_NEURON: False
  MASK_ON: True
  LOSS:
    SEGM_MASK_COEF: 8.0
    SEGM_DICE_COEF: 8.0

SOLVER:
  FROZEN_PARAMS: []
  BASE_LR: 0.0001
  LR_BACKBONE: 0.00002
  BACKBONE_NAMES: ['backbone.0',]
  LR_MASK_HEAD_MULT: 1
  EPOCHS: 15
  STEPS: [10, ]

TEST:
  NUM_OUT: 50