# This mask head is not train from scratch, thus we change lrs
MODEL:
  WEIGHTS: 'weights/r50_deformable_detr_plus_iterative_bbox_refinement-checkpoint.pth'
  BACKBONE: 'swin_l_p4w12'
  SHIFT_CLASS_NEURON: False
  MASK_ON: True
  LOSS:
    SEGM_MASK_COEF: 8.0
    SEGM_DICE_COEF: 8.0

SOLVER:
  FROZEN_PARAMS: []
  BASE_LR: 0.00005
  LR_BACKBONE: 0.00001
  BACKBONE_NAMES: ['backbone.0',]
  LR_MASK_HEAD_MULT: 1
  EPOCHS: 20
  STEPS: [10, ]
  BATCH_SIZE: 1


TEST:
  NUM_OUT: 50