MODEL:
  WEIGHTS: 'weights/r50_deformable_detr_plus_iterative_bbox_refinement-checkpoint.pth'
  MASK_ON: True
  BBX_GRADIENT_PROP: True
  LOSS:
    SEGM_MASK_COEF: 2.0
    SEGM_DICE_COEF: 2.0
    AUX_LOSS_WEIGHTING: True

SOLVER:
  FROZEN_PARAMS: []
  BASE_LR: 0.00001
  LR_BACKBONE: 0.000001
  LR_MASK_HEAD_MULT: 10
  EPOCHS: 25
  STEPS: [15, ]

TEST:
  NUM_OUT: 50